# Use official Node.js image
FROM node:current-alpine3.23

# Set working directory
WORKDIR /app

# Copy application source
COPY . .

# Expose app port
EXPOSE 3001

# Start the app
CMD ["node", "server.js"]
